sudo: required
services:
  - docker

before_install:
  - docker build -t saramsh123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saramsh123/docker-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-508153278417"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
